### ISSUE TITLE
Shell Script Invocation Error Group

### ISSUE THREAD

**Issue by Nitinbond** [AmilaDiman/ADCountryPicker#5]
sent 4440958 bytes  received 11186 bytes  8904288.00 bytes/sec
total size is 4409981  speedup is 0.99
Code Signing /Users/sandeepankumar/Library/Developer/Xcode/DerivedData/Lawzgrid-cjsccsrliyvatfhcghjcpfiqbope/Build/Products/Debug-iphoneos/Lawzgrid.app/Frameworks/ADCountryPicker.framework with Identity iPhone Developer: MAC DEVELOPER (xyd123)
/usr/bin/codesign --force --sign [ABC6D5981195AFA22BBFBA5362BCC0AD673E8FE4](url
![screen shot 2018-05-25 at 5 00 44 pm](https://user-images.githubusercontent.com/11436995/40542370-8edb0e46-603d-11e8-8b78-91143cbbd36b.png)
)  --preserve-metadata=identifier,entitlements '/Users/sandeepankumar/Library/Developer/Xcode/DerivedData/Lawzgrid-cjsccsrliyvatfhcghjcpfiqbope/Build/Products/Debug-iphoneos/Lawzgrid.app/Frameworks/ADCountryPicker.framework'
/Users/sandeepankumar/Library/Developer/Xcode/DerivedData/Lawzgrid-cjsccsrliyvatfhcghjcpfiqbope/Build/Products/Debug-iphoneos/Lawzgrid.app/Frameworks/ADCountryPicker.framework: errSecInternalComponent
Command /bin/sh failed with exit code 1

**Comment by AmilaDiman** [comment]
Did you try clearing you derived data?

**Comment by Nitinbond** [comment]
I cleared my derived data but error still occurred.

Nitin Kumar
Mob-No : +91-9005976013
Email : nitinbond@live.in<mailto:nitinbond@live.in>

On 26-May-2018, at 8:50 AM, AmilaDiman <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you try clearing you derived data?

**Comment by Nitinbond** [comment]
Any Solution ?

**Comment by AmilaDiman** [comment]
This should be a issue with your project setup I guess.
Try: https://stackoverflow.com/questions/31245373/cocoa-pods-shell-script-invocation-error

**Comment by Nitinbond** [comment]
which answer i'll try?
